//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArHeaderExtend
    {
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<double> PriorWarrantyPercentage { get; set; }
        public Nullable<double> CurrentWarrantyPercentage { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<double> ReservedFloat { get; set; }
        public Nullable<decimal> ReservedMoney1 { get; set; }
        public Nullable<decimal> ReservedMoney2 { get; set; }
        public Nullable<decimal> ReservedMoney3 { get; set; }
        public Nullable<int> ReservedInt1 { get; set; }
        public Nullable<int> ReservedInt2 { get; set; }
        public string ReservedStr { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
