//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArHeader
    {
        public string Src { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Pos { get; set; }
        public string AcctNo { get; set; }
        public Nullable<System.DateTime> FirstPymtDt { get; set; }
        public Nullable<System.DateTime> ContractDt { get; set; }
        public Nullable<decimal> AmtFin { get; set; }
        public Nullable<decimal> FinChg { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<decimal> CredLife { get; set; }
        public Nullable<decimal> AH { get; set; }
        public Nullable<decimal> PropIns { get; set; }
        public Nullable<decimal> UnEmp { get; set; }
        public Nullable<decimal> NonFile { get; set; }
        public Nullable<decimal> PaymentAmt { get; set; }
        public Nullable<decimal> SalesAmt { get; set; }
        public Nullable<decimal> SalesAmtTaxable { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> DownPay { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<int> IntRate { get; set; }
        public Nullable<decimal> UnpaidBal { get; set; }
        public Nullable<decimal> TotRefund { get; set; }
        public Nullable<decimal> Payoff { get; set; }
        public Nullable<decimal> FinFwd { get; set; }
        public Nullable<decimal> InsLifeFwd { get; set; }
        public Nullable<decimal> InsPropFwd { get; set; }
        public string Store { get; set; }
        public string SoldBy { get; set; }
        public string CnStatus { get; set; }
        public string AddrKeep { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<decimal> ALSSvc { get; set; }
        public Nullable<decimal> UCCFee { get; set; }
        public Nullable<decimal> Warranty { get; set; }
        public Nullable<int> WarrantyTerm { get; set; }
        public Nullable<decimal> WarrantyFwd { get; set; }
        public Nullable<decimal> DebtWaiver { get; set; }
        public Nullable<decimal> DebtWaiverFwd { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> LocationTypeStoredValue { get; set; }
        public string ParentAccountNo { get; set; }
        public Nullable<int> StatutoryID { get; set; }
        public int OriginalContractStatusTypeID { get; set; }
        public int InitialPaymentMethodTypeID { get; set; }
        public Nullable<int> FinancingTermsTypeID { get; set; }
        public string LenderDN { get; set; }
        public string LenderAN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
