//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArHeaderExtraInfo
    {
        public string AcctNo { get; set; }
        public string reserved1 { get; set; }
        public Nullable<int> reserved2 { get; set; }
        public Nullable<decimal> reserved3 { get; set; }
        public Nullable<decimal> reserved4 { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> PromptionTypeID { get; set; }
        public string SaleSummary { get; set; }
        public string ReferrerName { get; set; }
        public Nullable<int> ReferrerTypeID { get; set; }
        public Nullable<int> ContractAttributes { get; set; }
    }
}
