//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArMastfl
    {
        public string Src { get; set; }
        public string Status { get; set; }
        public string AcctNo { get; set; }
        public string Name { get; set; }
        public string CoMaker { get; set; }
        public string SSN { get; set; }
        public Nullable<decimal> CurBal { get; set; }
        public Nullable<System.DateTime> NextDueDt { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CoMakerDOB { get; set; }
        public string EmpBen { get; set; }
        public string MailCode { get; set; }
        public string Salesmn { get; set; }
        public string Active { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public string AcctFlag1 { get; set; }
        public string AcctFlag2 { get; set; }
        public string AcctFlag3 { get; set; }
        public string AcctFlag4 { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Pos { get; set; }
        public string AcctNo1 { get; set; }
        public string AcctNo2 { get; set; }
        public string Cmnt { get; set; }
        public string CoSSN { get; set; }
        public string CoAddr1 { get; set; }
        public string CoAddr2 { get; set; }
        public string CoCity { get; set; }
        public string CoState { get; set; }
        public string CoZip { get; set; }
        public string CoPhone { get; set; }
        public Nullable<decimal> DLNQ0 { get; set; }
        public Nullable<decimal> DLNQ1 { get; set; }
        public Nullable<decimal> DLNQ2 { get; set; }
        public Nullable<decimal> DLNQ3 { get; set; }
        public Nullable<decimal> DLNQ4 { get; set; }
        public Nullable<decimal> LateFees { get; set; }
        public System.Guid rowguid { get; set; }
        public string FlagRepo { get; set; }
        public string Zip4 { get; set; }
        public string CoZip4 { get; set; }
        public string DM { get; set; }
        public int DMCommandTypeID { get; set; }
        public Nullable<decimal> DLNQ5 { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> EffectiveContractDate { get; set; }
        public int ContractTypeTypeID { get; set; }
        public int CurrentContractStatusTypeID { get; set; }
        public int DocumentsStatusTypeID { get; set; }
        public int DeliveryStatusTypeID { get; set; }
        public Nullable<byte> PaymentFrequency { get; set; }
        public Nullable<decimal> DownpaymentDue { get; set; }
        public int DocumentLocationTypeID { get; set; }
        public Nullable<System.DateTime> ReceivedCorpDate { get; set; }
        public Nullable<System.DateTime> SentToLenderDate { get; set; }
        public Nullable<System.DateTime> SentToCollectionsDate { get; set; }
        public decimal RebateToCustomer { get; set; }
        public string RebateToCustomerCheckNo { get; set; }
        public decimal RebateToDownPayment { get; set; }
        public string RebateToDownPaymentCheckNo { get; set; }
        public decimal AllotRefundAmount { get; set; }
        public string AllotCheckNo { get; set; }
        public decimal CreditBalanceFwd { get; set; }
        public string CreditBalanceContract { get; set; }
        public bool CreditBalanceToDownPayment { get; set; }
        public Nullable<System.DateTime> FirstDelinquencyDate { get; set; }
        public Nullable<decimal> NoFaultReturnCredit { get; set; }
        public Nullable<System.DateTime> NoFaultReturnDate { get; set; }
        public bool IsArchived { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
