//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsDetail
    {
        public string AcctNo { get; set; }
        public string Item { get; set; }
        public string Dscrp { get; set; }
        public string NewUsed { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExtPrice { get; set; }
        public string SerialNo { get; set; }
        public string StockYN { get; set; }
        public string Location { get; set; }
        public string PONumber { get; set; }
        public string Mfg { get; set; }
        public string Fulfill { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> MerchandiseCodeStoredValue { get; set; }
        public Nullable<byte> RepoQuantity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> MerchandiseStatusTypeID { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Flag2 { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
    }
}
