//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YongTest.CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Src { get; set; }
        public string SSN { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmpBen { get; set; }
        public string MailCode { get; set; }
        public string Salesmn { get; set; }
        public string MilCiv { get; set; }
        public System.Guid rowguid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MI { get; set; }
        public string Suffix { get; set; }
        public string LenderSSN { get; set; }
        public string EmailAddress { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
